# Generated by Django 5.1.6 on 2025-02-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compreve_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streaminfo',
            unique_together={('uploaded_file', 'channel', 'title', 'category', 'start_time', 'timestamp')},
        ),
    ]
